### PR TITLE
Blog App: Controllers specs

### PR DESCRIPTION
**Pull request by Timbar09**
In this PR, I generated Rspec tests for requests.

**Changes**

- Installed the  `rails-controller-testing` gem.
- Populated view templates.
- Generated request spec tests for the `users` and `posts` controllers.
- Checked the response status for both controllers.
- Checked whether the template was rendered for both controllers.
- Checked if the response body includes the correct placeholder text for both controllers.

### CODE REVIEW

**Review by cynthiainga — CHANGES_REQUESTED** [review]
Hi @Timbar09, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!



## Highlights

- [ ] All tests are passing ✔️ 
- [ ] Correct Gitflow ✔️ 
- [ ] Descriptive PR ✔️ 


## Required Changes ♻️

- [ ] The MIT link in your README file is broken, please kindly fix that and make sure everything is okay 🙃 

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you consider them as they can improve your code._


Cheers, and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please remember to tag me in your question so I can get the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by Timbar09** [comment]
Thanks for the feedback, @cynthiainga. I'm on it.

**Review by Munsa1 — APPROVED** [review]
Hi @Timbar09, 
congratulations-1

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights
Made Requested Change :heavy_check_mark: 
Good Communication :heavy_check_mark: 

## Optional suggestions
N/A

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by Timbar09** [comment]
Thanks, @Munsa1 for the feedback and for approving my PR. Have a wonderful day. 🙃

**Pull request merged**
